#!/usr/bin/env bash

DEM_PROFILE_NAME="minimal"

DEM_INSTALL_CORE=true
DEM_INSTALL_DEVELOPMENT=false
DEM_INSTALL_DOCKER=false
DEM_INSTALL_DATABASE=false
DEM_INSTALL_OFFICE=false
DEM_INSTALL_FONTS=false
DEM_INSTALL_UTILITIES=true
DEM_INSTALL_SECURITY=false
DEM_INSTALL_MONITORING=false